### ISSUE TITLE
Android build failing

### ISSUE THREAD

**Issue by codemercenary** [leapmotion/autowiring#792]
The failure is due to our `CoreThreadLinux` adjustments in #786.  Here's the error:

```
src/autowiring/CoreThreadLinux.cpp: In member function 'void BasicThread::SetThreadPriority(ThreadPriority)':
src/autowiring/CoreThreadLinux.cpp:37:14: error: 'SCHED_IDLE' was not declared in this scope
     policy = SCHED_IDLE;
```

We need to fix this, or turn off this feature on Android.
