### PR TITLE
Fix a Build Error of Android

### LINKED ISSUE #792: Android build failing
The failure is due to our `CoreThreadLinux` adjustments in #786.  Here's the error:

```
src/autowiring/CoreThreadLinux.cpp: In member function 'void BasicThread::SetThreadPriority(ThreadPriority)':
src/autowiring/CoreThreadLinux.cpp:37:14: error: 'SCHED_IDLE' was not declared in this scope
     policy = SCHED_IDLE;
```

We need to fix this, or turn off this feature on Android.

### PR DESCRIPTION
**Pull request by hham**
- SCHED_IDLE is not included in Kernel 3.1.x.

Fixes #792

### CODE REVIEW

**Comment by codemercenary** [comment]
Thanks, @hham !
